[project]
name = "ct-viewer"
version = "0.1.0"
description = "TUI for viewing PubChem classification XML files"
readme = "README.md"
authors = [
    { name = "Tiejun Cheng", email = "need47@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "textual",
]

[project.scripts]
ct-viewer = "ct_viewer:main"
cv = "ct_viewer:main"

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"
